/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package museoclient;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import museocommon.DataUser;
import museocommon.MuseoInt;

/**
 *
 * @author pinedo
 */
public class Container extends javax.swing.JFrame {

    MuseoInt connection;
    public List<DataUser> response = null;

    /**
     * Creates new form Container
     */
    public Container() {
        initComponents();
        connection = connect();

        Login window = new Login(this, connection);
        ContentMain.add(window);
        window.show();

        menuadmin.setVisible(false);
        menuOptions.setVisible(false);
    }

    MuseoInt connect() {
        String nombreNodo;
        InputStreamReader ent = new InputStreamReader(System.in);
        BufferedReader buf = new BufferedReader(ent);
//        System.out.println("Introducir el nombre del nodo del registro RMI:");
//        nombreNodo = buf.readLine();
        nombreNodo = "localhost";
//        System.out.println("Introducir el número de puerto del registro RMI:");
//        String numPuerto = buf.readLine();
        String numPuerto = "8881";
        
        String URLRegistro = "rmi://" + nombreNodo + ":" + numPuerto + "/holaMundo";
        MuseoInt h = null;
        try {
            h = (MuseoInt) Naming.lookup(URLRegistro);
        } catch (NotBoundException ex) {
            System.out.println(ex);
        } catch (MalformedURLException ex) {
            System.out.println(ex);
        } catch (RemoteException ex) {
            System.out.println(ex);
        }

        System.out.println("Busqueda completa, conectado ");

        return h;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        ContentMain = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuadmin = new javax.swing.JMenu();
        optPrices = new javax.swing.JMenuItem();
        optReport = new javax.swing.JMenuItem();
        menuOptions = new javax.swing.JMenu();
        optIO = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar3.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar3.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ContentMainLayout = new javax.swing.GroupLayout(ContentMain);
        ContentMain.setLayout(ContentMainLayout);
        ContentMainLayout.setHorizontalGroup(
            ContentMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        ContentMainLayout.setVerticalGroup(
            ContentMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        menuadmin.setText("Administrator");

        optPrices.setText("Prices");
        menuadmin.add(optPrices);

        optReport.setText("Report");
        optReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optReportActionPerformed(evt);
            }
        });
        menuadmin.add(optReport);

        jMenuBar2.add(menuadmin);

        menuOptions.setText("Options");

        optIO.setText("Entrada / Salida");
        optIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optIOActionPerformed(evt);
            }
        });
        menuOptions.add(optIO);

        jMenuBar2.add(menuOptions);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContentMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContentMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optIOActionPerformed
        InputOutput window = new InputOutput(connection);
        ContentMain.add(window);
        window.show();
    }//GEN-LAST:event_optIOActionPerformed

    private void optReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optReportActionPerformed
        Report window = new Report(connection);
        ContentMain.add(window);
        window.show();
    }//GEN-LAST:event_optReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Container.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Container().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane ContentMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenu menuOptions;
    public javax.swing.JMenu menuadmin;
    private javax.swing.JMenuItem optIO;
    private javax.swing.JMenuItem optPrices;
    private javax.swing.JMenuItem optReport;
    // End of variables declaration//GEN-END:variables
}
